#!/usr/bin/env python3
"""
Generate a cryptographically secure SECRET_KEY for Flask.

Usage
-----
    python scripts/generate_secret_key.py

    # Set directly in the environment:
    export SECRET_KEY=$(python scripts/generate_secret_key.py)

    # Add to .env:
    echo "SECRET_KEY=$(python scripts/generate_secret_key.py)" >> .env

The output is a 64-character hex string (256 bits of entropy) generated by
the OS's cryptographically secure random number generator (os.urandom).
"""

import secrets

print(secrets.token_hex(32))
